name: CI

on:
  push:
    branches:
      - 'main'
      - 'develop'
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  testsuite:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.1']
    name: PHP ${{ matrix.php-version }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, intl, pdo_sqlite
        coverage: none

    - name: Composer install
      run: composer install --prefer-dist --no-interaction

    - name: Run PHPUnit
      run: |
        cp config/app_local.example.php config/app_local.php
        vendor/bin/phpunit
      env:
        DATABASE_URL: sqlite://./testdb.sqlite
        DATABASE_TEST_URL: sqlite://./testdb.sqlite

  coding-standard:
    name: Coding Standard
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, intl
        coverage: none

    - name: Composer install
      run: composer install

    - name: Run PHP CodeSniffer
      run: composer cs-check

  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, intl
        coverage: none

    - name: Composer install
      run: composer require --dev phpstan/phpstan:^1.0.0

    - name: Run phpstan
      run: vendor/bin/phpstan
